version: '3'

services:
  ld-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=projects-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5555:5432'
volumes:
  pgdata: