apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-api
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: projects-api
  template:
    metadata:
      labels:
        app: projects-api
    spec:
      containers:
      - name: projects-api
        image: "giuco/projects-api:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: USER
            value: "postgres"
          - name: PASSWORD
            value: "password"
          - name: HOST
            value: "host.minikube.internal"
          - name: DB_PORT
            value: "5555"
          - name: DB_NAME
            value: "projects-db"
          - name: APP_PORT
            value: "8080"
          - name: JWT_SECRET_KEY
            value: "secret_key"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: projects-api
spec:
  selector:
    name: projects-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080